### ISSUE TITLE
Getting names associated with devices in single call

### ISSUE THREAD

**Issue by gciluffo** [Geotab/mg-api-node#4]
Currently is there a way to call geotab API and get list of deviceId's along with the user that is assigned to that device? Currently we have to GET all logRecords which contains deviceId's and geometry and make a separate call for each record to GET device by ID to get the name associated with that device. So current implementation is similar to this:

```  
   api.call('Get', {
            'typeName': 'LogRecord',
            'search': {
                'fromDate': new Date().toISOString()
            }
        }, (err, data) => {
           // Iterate through records and make call for each record
        });
```

Then we have to loop through each item in records array and call for each device to get the name associated with it.

```
api.call('Get', {
            'typeName': 'Device',
            'search': {
                'id': logData.device.id
            }
        }, (err, result) => {
        });
```
Is there some way we can do an inner join on the data returned on both calls by deviceId?

**Comment by beefo** [comment]
There's no way to join the data server side. Though a couple of options come to mind to speed it up. Typically what I would do is keep a local expirable cache of devices or perhaps iterate the logs to find the unique device id's, then package the requests into a multicall and populate the logs from the results.
Device records generally change infrequently which makes it a good candidate for caching optimization.

**Comment by gciluffo** [comment]
Okay thanks for the reply.
