### ISSUE TITLE
Using promises

### ISSUE THREAD

**Issue by mebibou** [Geotab/mg-api-node#6]
Please update lib to use promises

**Comment by mebibou** [comment]
Currently, I have to use `promisify` to make the code more readable:
```javascript
const GeotabAPI = require('mg-api-node');
const { promisify } = require('util');

const run = async () => {
  const api = new GeotabAPI(username, password, database);
  const authenticate = promisify(api.authenticate);
  const call = promisify(api.call);

  const { userName } = await authenticate();

  const user = await call('Get', {
    typeName: 'User',
    search: {
      name: userName
    }
  });
  console.log('user', user);
};
```

**Comment by adlenafane** [comment]
@beefo Are you willing to switch to a promise-only package or do you want to handle both options?

**Comment by beefo** [comment]
Please checkout https://github.com/Geotab/mg-api-js which supports nodejs and client js. This project (mg-api-node) will be deprecated in favor of a mg-api.js.
